<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

/**
 * Print admin page(s) tabs
 * 
 * @param  string $active Active tab title
 */
function print_admin_tabs($active = 'Setup')
{
    $tabs = array(
        array('title' => 'Setup', 'url' => 'moneymannager/admin/setup.php?mainmenu=home'),
        array('title' => 'Changelog', 'url' => 'moneymannager/admin/changelog.php?mainmenu=home'),
        array('title' => 'About', 'url' => 'moneymannager/admin/about.php?mainmenu=home')
    );

    foreach ($tabs as $key => $tab)
    {
        if ($tab['title'] == $active) {
            $tabs[$key]['active'] = true;
            break;
        }
    }

    print_tabs($tabs, 'MoneyMannager', 'moneymannager.png@moneymannager', -1);
}
