<?php

/**
 * This file was generated by DAMB
 *
 * @copyright   Copyright (c) 2019 - 2020, AXeL-dev
 * @license     GPL
 * @link        https://github.com/AXeL-dev/damb
 */

// Load Dolibarr environment (mandatory)
if (false === (@include_once '../../main.inc.php')) { // From htdocs directory
    require_once '../../../main.inc.php'; // From "custom" directory
}

// Load page & moneymannager lib
dol_include_once('moneymannager/lib/page.lib.php');
dol_include_once('moneymannager/lib/moneymannager.lib.php');
dol_include_once('moneymannager/lib/dolistore.lib.php');

// Load module class
dol_include_once('moneymannager/core/modules/modMoneyMannager.class.php');

// Control access to page
control_access('$user->admin');

/**
 * View
 */

print_header('About', array('admin', 'moneymannager@moneymannager'));

print_subtitle('About', 'title_generic.png', 'link:modules_list');

print_admin_tabs('About');

$module = new modMoneyMannager(null);

load_template('moneymannager/tpl/about.tpl.php', array(
    'module_name' => $module->name,
    'module_desc' => $module->description,
    'module_picture' => 'moneymannager.png@moneymannager',
    'module_version' => $module->version,
    'module_url' => '#',
    'author_name' => $module->editor_name,
    'author_url' => $module->editor_url,
    'author_email' => '',
    'author_dolistore_url' => '#'
));

print_footer(true);
